# Generated by Django 4.1.dev20220219193601 on 2022-03-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='company',
            name='web',
            field=models.CharField(default='example.com', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='salary',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
