# Generated by Django 4.1.dev20220219193601 on 2022-03-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='web',
            field=models.CharField(default='example.com', max_length=150),
        ),
    ]
