# Generated by Django 4.1.dev20220219193601 on 2022-03-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_companyprofile_password1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='company',
            field=models.CharField(default='prueba', max_length=150, verbose_name='Compañia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.CharField(default='prueba', max_length=1000, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='location',
            field=models.CharField(default='prueba', max_length=150, verbose_name='Ubicación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='modality',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Remoto', 'Remoto')], default='prueba', max_length=50, verbose_name='Modalidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='salary',
            field=models.IntegerField(blank=True, default=0, verbose_name='Salario'),
        ),
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default='prueba', max_length=150, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
