# Generated by Django 4.1.dev20220219193601 on 2022-03-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_offer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='logo',
            field=models.ImageField(default='offer/offer-default-logo.png', upload_to='user_directory_path_logo'),
        ),
    ]
