# Generated by Django 4.1.dev20220219193601 on 2022-03-11 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_offer_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='user_applications',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
