# Generated by Django 4.1.dev20220219193601 on 2022-03-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_offer_user_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='user_applications',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_offer_id',
            field=models.ManyToManyField(blank=True, to='home.offer'),
        ),
    ]
